version: "3.8"

services:
  server:
    container_name: server
    restart: always
    build:
      context: ./server
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
      - 5000:5000
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./server/.env
    command: npm run server
  client:
    container_name: client
    restart: always
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start
